#include <avr/io.h>

#include "pin_config.h"

void data_input_mode() {
	SET_INPUT(PIN_D0);
	SET_INPUT(PIN_D1);
	SET_INPUT(PIN_D2);
	SET_INPUT(PIN_D3);
	SET_INPUT(PIN_D4);
	SET_INPUT(PIN_D5);
	SET_INPUT(PIN_D6);
	SET_INPUT(PIN_D7);

	CLEAR_PULLUP(PIN_D0);
	CLEAR_PULLUP(PIN_D1);
	CLEAR_PULLUP(PIN_D2);
	CLEAR_PULLUP(PIN_D3);
	CLEAR_PULLUP(PIN_D4);
	CLEAR_PULLUP(PIN_D5);
	CLEAR_PULLUP(PIN_D6);
	CLEAR_PULLUP(PIN_D7);
}

void data_output_mode() {
	SET_OUTPUT(PIN_D0);
	SET_OUTPUT(PIN_D1);
	SET_OUTPUT(PIN_D2);
	SET_OUTPUT(PIN_D3);
	SET_OUTPUT(PIN_D4);
	SET_OUTPUT(PIN_D5);
	SET_OUTPUT(PIN_D6);
	SET_OUTPUT(PIN_D7);
}

void init_pins() {
	// Flash outputs
	SET_PIN_HIGH(PIN_VPP_12V_EN_L); // Start in (safe) read mode
	SET_OUTPUT(PIN_VPP_12V_EN_L);
	SET_PIN_HIGH(PIN_A9_VPP_EN_L);
	SET_OUTPUT(PIN_A9_VPP_EN_L);
	SET_OUTPUT(PIN_PGM_L);
	SET_OUTPUT(PIN_CE_L);
	SET_OUTPUT(PIN_OE_L);

	// Shift register outputs
	SET_OUTPUT(PIN_A_RCK);
	SET_OUTPUT(PIN_A_SCK);
	SET_OUTPUT(PIN_A_SER);
	SET_OUTPUT(PIN_A_OE_L);

	SET_OUTPUT(PIN_A16);
}
